<a href="https://colab.research.google.com/github/PriyankaSharma0925/PriyankaSharma0925/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introduction to tensorflow


In [2]:
import tensorflow as tf
print(tf.__version__)

2.8.0


Creatinfg tensor with tf.constant

In [3]:
scalar =tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

Check the no. of dimensions

In [4]:
scalar.ndim

0

Create a vector

In [5]:
vector=tf.constant([10,3])
vector


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  3], dtype=int32)>

In [10]:
# creating a matrix

matrix=tf.constant([[2,3,4,5],
                    [3,5,5,8]])
matrix

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[2, 3, 4, 5],
       [3, 5, 5, 8]], dtype=int32)>

In [11]:
print(matrix.ndim)

2


In [15]:
#creating a tensor
tensor=tf.constant([[[2,1,4],
                     [6,7,6]],
                    [[3,4,5],
                    [9,6,7]]])

In [16]:
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[2, 1, 4],
        [6, 7, 6]],

       [[3, 4, 5],
        [9, 6, 7]]], dtype=int32)>

In [14]:
tensor.ndim

3

# Creating tensor with tf.variable

In [17]:
changeable_tensor=tf.Variable([10,4,5])
unchangeable_tensor=tf.constant([10,4,8])
changeable_tensor
unchangeable_tensor


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10,  4,  8], dtype=int32)>

In [18]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([10,  4,  5], dtype=int32)>

In [19]:
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [20]:
changeable_tensor[0].assign(17)

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([17,  4,  5], dtype=int32)>

In [21]:
unchangeable_tensor[0].assign(19)  ## throws error

AttributeError: ignored