<a href="https://colab.research.google.com/github/PriyankaSharma0925/PriyankaSharma0925/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introduction to tensorflow


In [ ]:
import tensorflow as tf
print(tf.__version__)

2.8.0


Creatinfg tensor with tf.constant

In [ ]:
scalar =tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

Check the no. of dimensions

In [ ]:
scalar.ndim

0

Create a vector

In [ ]:
vector=tf.constant([10,3])
vector


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  3], dtype=int32)>

In [ ]:
# creating a matrix

matrix=tf.constant([[2,3,4,5],
                    [3,5,5,8]])
matrix

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[2, 3, 4, 5],
       [3, 5, 5, 8]], dtype=int32)>

In [ ]:
print(matrix.ndim)

2


In [ ]:
#creating a tensor
tensor=tf.constant([[[2,1,4],
                     [6,7,6]],
                    [[3,4,5],
                    [9,6,7]]])

In [ ]:
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[2, 1, 4],
        [6, 7, 6]],

       [[3, 4, 5],
        [9, 6, 7]]], dtype=int32)>

In [ ]:
tensor.ndim

3

# Creating tensor with tf.variable

In [ ]:
changeable_tensor=tf.Variable([10,4,5])
unchangeable_tensor=tf.constant([10,4,8])
changeable_tensor
unchangeable_tensor


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10,  4,  8], dtype=int32)>

In [ ]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([10,  4,  5], dtype=int32)>

In [ ]:
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
# It will throw error as constant tensors are immutable.
# changeable_tensor[0].assign(17) 

### Creating Random Tensor



In [23]:
tensor_1=tf.random.Generator.from_seed(6)
tensor_1=tensor_1.normal(shape=(3,2))
tensor_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.97061104, -1.0242516 ],
       [-0.6544423 , -0.29738766],
       [-1.3240396 ,  0.28785667]], dtype=float32)>

###
Result will be same on every time we run the above code cell
<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.97061104, -1.0242516 ],
       [-0.6544423 , -0.29738766],
       [-1.3240396 ,  0.28785667]], dtype=float32)>

In [26]:
tensor_2=tf.random.Generator.from_seed(6)
tensor_2=tensor_2.normal(shape=(3,2))
tensor_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.97061104, -1.0242516 ],
       [-0.6544423 , -0.29738766],
       [-1.3240396 ,  0.28785667]], dtype=float32)>