<a href="https://colab.research.google.com/github/PriyankaSharma0925/PriyankaSharma0925/blob/main/IndexingAndExpandingTensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf


In [3]:
print(tf.__version__)

2.8.0


In [4]:
tensor1=tf.constant([2,3,4,5,6,7,8,9],shape=(1,1,2,4))
tensor1

<tf.Tensor: shape=(1, 1, 2, 4), dtype=int32, numpy=
array([[[[2, 3, 4, 5],
         [6, 7, 8, 9]]]], dtype=int32)>

In [5]:
tf.zeros(shape=[2,2,3,3,2])

<tf.Tensor: shape=(2, 2, 3, 3, 2), dtype=float32, numpy=
array([[[[[0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.]]]],



       [[[[0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.]]]]], dtype=float32)>

In [6]:
print(tensor1.ndim)

4


In [7]:
tensor_2=tf.zeros(shape=(9,2,3,4,6))

In [8]:
print(tensor_2.ndim)

5


In [9]:
print(tensor_2[0].shape)

(2, 3, 4, 6)


In [10]:
print(tensor_2.shape[0])

9


In [11]:
tensor_2[0].shape

TensorShape([2, 3, 4, 6])

In [12]:
tensor1


<tf.Tensor: shape=(1, 1, 2, 4), dtype=int32, numpy=
array([[[[2, 3, 4, 5],
         [6, 7, 8, 9]]]], dtype=int32)>

In [13]:
tensor1[:1,:1,:1:1]

<tf.Tensor: shape=(1, 1, 1, 4), dtype=int32, numpy=array([[[[2, 3, 4, 5]]]], dtype=int32)>